default: client server

client:
	gcc -Wall -Wextra -lz -o lab1b-client lab1b-client.c

server:
	gcc -Wall -Wextra -lz -o lab1b-server lab1b-server.c

clean:
	rm -f lab1b-client lab1b-server *.tar.gz

dist:
	tar -czf lab1b-604805167.tar.gz lab1b-client.c lab1b-server.c README Makefile
