#NAME: Kana Yabuno,
#EMAIL: kana0111@g.ucla.edu
#ID: 404849285

default:
	gcc -Wall -Wextra -o lab3a lab3a.c
dist:
	tar -cvzf lab3a-604805167.tar.gz lab3a.c Makefile README ext2_fs.h
clean:
	rm -f *tar.gz lab3a
